layout: default
encoding: utf-8
title: imazzine.pages
description: >-
  Short description of imazine.pages and imazzine.project
  optimized for search engines here.
url: https://imazzine.github.io/
permalink: /:categories/:lang/:title/
highlighter: rouge
markdown: kramdown
collections:
  notes:
    output: true
  papers:
    output: true