layout: default
encoding: utf-8
title: imazzine.pages
description: >-
  Short description of imazine.pages and imazzine.project
  optimized for search engines here!
url: https://imazzine.github.io/
highlighter: rouge
markdown: kramdown
collections:
  landing:
    output: true
  papers:
    output: true
    permalink: /:categories/:name/
t:
  en:
    table_of_content: 'Table of content'
  ru:
    table_of_content: 'Содержание'