layout: default
encoding: utf-8
title: imazzine.pages
description: >-
  Short description of imazine.pages and imazzine.project
  optimized for search engines here.
url: https://imazzine.github.io/
highlighter: rouge
markdown: kramdown
collections:
  notes:
    output: true
    permalink: /:collection/:categories/:title/
  papers:
    output: true
    permalink: /:collection/:categories/:title/